### ISSUE TITLE
${proxyPath} not correctly substituted on welcome page

### ISSUE THREAD

**Issue by ScreamingHawk** [claudioc/jingo#211]
A couple of references to `${proxyPath}` are not being substituted on the welcome page. 

`welcome.pug` lines 8 and 9. 

`layout.pug` lines 67 and 71. 

What's weird is that `layout.pug` line 27 seems to substitute just fine. 

I haven't been able to find a fix as I'm not familiar with the frameworks used in Jingo, but I imagine it's relatively simple.

**Comment by claudioc** [comment]
Yeah, I _just_ encountered the same problem with a fresh installation. I am on it. Thanks

**Comment by ScreamingHawk** [comment]
Noticed there are a couple other paths that don't have proxyPath in them that probably should. e.g. `layout.pug` line 35. 

I don't use proxyPath so it's a non-issue for me but something to look in to. 

Thanks for maintaining this project. It's been a life saver for me.

**Comment by claudioc** [comment]
When using the `anchor` mixin, the proxyPath is added automatically.

The bug was related to the jade-pug migration and you can read more about it here: https://pugjs.org/api/migration-v2.html (it's the "attribute interpolation", where _when used on attributes of a mixin_, needs the backticks (it's just ES2015)), otherwise, just use the `#{blah}` syntax.
